# -*- coding: utf-8 -*-
"""
Created on Thu Mar 26 12:36:17 2015

@author: ci381
"""
#Question 2
##Each new term in the Fibonacci sequence is generated by adding the previous 
##two terms. By starting with 1 and 2, the first 10 terms will be:
##
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
##By considering the terms in the Fibonacci sequence whose values do not exceed 
##four million, find the sum of the even-valued terms.
#
#fib1 = 1
#fib2 = 2
#
#fibs = 0
#
#while fib2<=4000000:
#    if fib2%2==0:
#        fibs += fib2
#    fib2 = fib2 + fib1
#    fib1 = fib2 - fib1
#   
#print(fibs)    

#Question 3 Largest prime factor
#Problem 3
#The prime factors of 13195 are 5, 7, 13 and 29.
#
#What is the largest prime factor of the number 600851475143 ?
baka=600851475143
bakafacts = [i for i in range(baka+1) if i!=0 and baka%i==0]
print(max(bakafacts))
